name: json2csv
version: 1.0.0
description: JSON to CSV Library
authors:
- Kenneth Endfinger <k.endfinger@dglogik.com>
homepage: https://github.com/dglogik/JSON-to-CSV
dev_dependencies:
  yaml: 2.0.0
  hop: 0.31.0+1
